version: '3.4'

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    volumes:
      - ./mc_server:/data
    environment:
      EULA: "TRUE"
      VERSION: "1.14.4"
      TYPE: "SPIGOT"
    restart: unless-stopped
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mc-twitch-sync:latest
    container_name: mc-twitch-sync
    volumes:
      - ./backend:/opt/app/backend
    command: /init
    working_dir: /opt/app/backend
    env_file:
      - ./backend/.env
    ports:
      - 8000:80
    expose:
      - 8000
    depends_on:
      - db
    environment:
      - LOG_LEVEL=DEBUG
    restart: unless-stopped
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres


