"""init

Revision ID: 9fb9a1c40f0b
Revises: 
Create Date: 2019-12-24 14:59:20.116008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb9a1c40f0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('twitch_nickname', sa.String(length=255), nullable=False),
    sa.Column('twitch_id', sa.Integer(), nullable=True),
    sa.Column('expire_date', sa.Date(), nullable=True),
    sa.Column('minecraft_nickname', sa.String(length=255), nullable=True),
    sa.Column('minecraft_uuid', sa.String(length=255), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('twitch_id'),
    sa.UniqueConstraint('twitch_nickname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
