"""add_is_member

Revision ID: dcefb80b2257
Revises: 9fb9a1c40f0b
Create Date: 2019-12-25 19:16:59.686817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcefb80b2257'
down_revision = '9fb9a1c40f0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_member', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_member')
    # ### end Alembic commands ###
